USE NEWBIE;

GO

CREATE TABLE dbo.T_WAREHOUSE

(
WAREHOUSE_ID INT NOT NULL
, WAREHOUSE_NAME NVARCHAR(64) NOT NULL
, SQUARE_TRADE REAL
, CONSTRAINT PK_T_WAREHOUSE PRIMARY KEY CLUSTERED ( WAREHOUSE_ID )
);

GO

CREATE TABLE dbo.T_ARTICLE

(
ARTICLE_ID INT NOT NULL
, ARTICLE_NAME NVARCHAR(64) NOT NULL
, COST_PRICE REAL
, SHELF_LIFE INT
, CONSTRAINT PK_T_ARTICLE PRIMARY KEY CLUSTERED ( ARTICLE_ID )
);

GO

CREATE TABLE dbo.T_DAY

(
DAY_ID DATE NOT NULL
, WEEK_ID INT NOT NULL
, MONTH_ID INT NOT NULL
, YEAR_ID INT NOT NULL
, CONSTRAINT PK_T_DAY PRIMARY KEY CLUSTERED ( DAY_ID )
);

GO

CREATE TABLE dbo.T_SALES

(
ARTICLE_ID INT NOT NULL
, WAREHOUSE_ID INT NOT NULL
, DAY_ID DATE NOT NULL
, SALE_QNTY REAL
, CONSTRAINT PK_T_SALES PRIMARY KEY CLUSTERED ( DAY_ID, WAREHOUSE_ID, ARTICLE_ID )
, CONSTRAINT FK_T_ARTICLE FOREIGN KEY ( ARTICLE_ID ) REFERENCES dbo.T_ARTICLE( ARTICLE_ID )
, CONSTRAINT FK_T_WAREHOUSE FOREIGN KEY ( WAREHOUSE_ID ) REFERENCES dbo.T_WAREHOUSE( WAREHOUSE_ID )
, CONSTRAINT FK_T_DAY FOREIGN KEY ( DAY_ID ) REFERENCES dbo.T_DAY( DAY_ID )
);

GO