USE [master]
GO
CREATE DATABASE [FS] ON 
( FILENAME = N'F:\MSSQL\DATA\FS.mdf' ),
( FILENAME = N'F:\MSSQL\DATA\FS_log.ldf' ),
FILEGROUP [FileStreamGroup] CONTAINS FILESTREAM DEFAULT 
( NAME = N'FSTR', FILENAME = N'F:\MSSQL\DATA\FILESTREAM' )
 FOR ATTACH
GO


ALTER DATABASE [FS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FS] SET ARITHABORT OFF 
GO

ALTER DATABASE [FS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FS] SET RECOVERY FULL 
GO

ALTER DATABASE [FS] SET  MULTI_USER 
GO

ALTER DATABASE [FS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FS] SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'CATALOG' ) 
GO

ALTER DATABASE [FS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FS] SET  READ_WRITE 
GO
